# Original config provided by Karol Nowakowski <karol@koeki-u.ac.jp>
# Used in continued pretraining for Ainu https://arxiv.org/pdf/2301.07295.pdf

common:
  fp16: false
  log_format: json
  log_interval: 200

checkpoint:
  save_interval_updates: 10000
  keep_interval_updates: 5
  no_epoch_checkpoints: true

task:
  _name: audio_pretraining
  data: ???
  max_sample_size: 150000
  min_sample_size: 16000
  normalize: true

dataset:
  num_workers: 6
  max_tokens: 150000
  skip_invalid_size_inputs_valid_test: true

distributed_training:
  ddp_backend: no_c10d

criterion:
  _name: wav2vec
  infonce: true
  log_keys: ["prob_perplexity","code_perplexity","temp"]
  loss_weights: [0.1, 0]

optimization:
  max_update: 100000
  lr: [0.0001]
  update_freq: [128]

optimizer:
  _name: adam
  adam_betas: (0.9,0.98)
  adam_eps: 1e-06
  weight_decay: 0.01

lr_scheduler:
  _name: polynomial_decay
  warmup_updates: 8000

model:
  _name: wav2vec2
  quantize_targets: true
  extractor_mode: layer_norm
  layer_norm_first: true
  final_dim: 768
  latent_temp: [2.0,0.1,0.999995]
  encoder_layerdrop: 0.05
  dropout_input: 0.1
  dropout_features: 0.1
  feature_grad_mult: 0.1
  conv_bias: true

  encoder_layers: 24
  encoder_embed_dim: 1024
  encoder_ffn_embed_dim: 4096
  encoder_attention_heads: 16
